# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!
STRIPE_PUBLISHABLE_KEY="pk_test_51Nt7AiSH9YUmBAon7pUfkMU35JCKVyW45rs65kxwPhtLqnZqbbMKqaKuIrUZNZU6p93XaMFC0380ZzLtEWN5MhvR00oqRfleFf"
STRIPE_SECRET_KEY="sk_test_51Nt7AiSH9YUmBAonNnHxyy8O1P3ZBiBwh8bQGcUtasqUT3BA9ENUGDZHdQHt4FclVryytBhWMuERk70ql7EoZDMy00wJQ2FZjb"